"""Enrichment data extracted from web_fetch_exa results on /kontakt pages.
Format: company_name -> dict with email/phone/contact_person/extra
"""

ENRICH = {
    "Centrum Drewna i Kompozytu": {
        "email": "wyceny@ecentrumdrewna.pl",
        "phone": "+48 698 948 712",
        "phone_extra": "+48 696 678 009 (dział techniczny)",
        "contact_person": "Piotr Czuk",
        "position": "Właściciel",
        "address": "ul. Kresowa 6, 04-206 Warszawa",
    },
    "Drewnotex": {
        "email": "j.michalski@drewnotex.pl",
        "phone": "+48 782 149 040",
        "contact_person": "Jakub Michalski",
        "position": "Inwestycje i współpraca",
        "phone_extra": "Rafał Mazur (płyty/podłogi) +48 505 454 400 rafal.m@drewnotex.pl | Maciej Grzędzicki (drewno) +48 787 727 313 maciej.g@drewnotex.pl | Bartosz Bełkowski (akcesoria) +48 606 751 036 handel@drewnotex.pl",
        "address": "Tywola 1, 87-300 Brodnica",
    },
    "Bober Drewno Skandynawskie": {
        "email": "biuro@boberdrewno.pl",
        "phone": "+48 663 848 437",
        "address": "Stołpie 14C, 22-151 Stołpie",
    },
    "PRO-DREW": {
        "email": "prodrew34@wp.pl",
        "phone": "+48 509 897 455",
        "address": "Topolnica 34, 07-214 Zatory",
    },
    "Stamadrew": {
        "email": "krzysztof@stamadrew.pl",
        "phone": "+48 533 306 056",
        "contact_person": "Krzysztof Bucki",
        "position": "Obsługa Podmiotów Gospodarczych",
        "phone_extra": "Sebastian Kucharski +48 512 791 166 sebastian@stamadrew.pl | Ewa Góra +48 609 733 343 ewa@stamadrew.pl | Wacław Góra +48 693 999 086 biuro@stamadrew.pl | Adrian Góra +48 535 886 888 adrian@stamadrew.pl",
        "address": "Czechowice-Dziedzice DK1 + Oświęcim ul. Kolbego 13",
    },
    "Global Biznes Warszawa": {
        "email": "info@global-biznes.pl",
        "phone": "+48 798 521 521",
        "contact_person": "Łukasz Olędzki",
        "position": "Zarząd",
        "phone_extra": "Arkadiusz Gumulski (handel) +48 790 339 123 a.gumulski@global-biznes.pl | Tomasz Synowiecki +48 513 503 535 | Emil Dziurdziak +48 513 503 228 | Maciej Michalski +48 790 578 979 | Martyna Kieszek +48 530 133 283",
        "address": "ul. Warszawska 415, Koczargi Nowe, 05-082 Stare Babice",
    },
    "MAT-TAR": {
        "email": "biuro@mat-tar.pl",
        "phone": "+48 660 091 696",
        "contact_person": "Andrzej Herzog",
        "position": "Kierownik Działu Sprzedaży i Marketingu",
        "phone_extra": "Wojciech Buszyk (zapytania) +48 668 008 111 | Ewa Działoszyńska (zamówienia) +48 539 909 956 zamowienia@mat-tar.pl | Dawid Walędziak (export) +48 532 744 178 dawid@mat-tar.pl | Magdalena Anioł (meble na wymiar) +48 532 744 183 meble@mat-tar.pl",
        "address": "Koźminiec 127, 63-330 Dobrzyca",
    },
    "Tartak Forest": {
        "email": "forest@firmaforest.pl",
        "phone": "+48 607 450 253",
        "contact_person": "Marek Wiatrzyk",
        "position": "Właściciel",
        "address": "Modryniec 138, 22-530 Mircze",
    },
    "Pimex - Deski elewacyjne": {
        "email": "krakow@pimex.pl",
        "phone": "+48 606 323 085",
        "phone_extra": "+48 12 652 77 48 (salon Kraków) | +48 606 323 019 (Książnice/produkcja)",
        "address": "ul. Nad Serafą 56A, 30-864 Kraków (salon) | Książnice 163, 32-420 Gdów (siedziba/produkcja)",
    },
    "Sordrew": {
        "email": "sordrew@sordrew.pl",
        "phone": "+48 512 287 058",
        "contact_person": "Anna Szczepańczyk-Baron",
        "position": "Dział handlowy",
        "phone_extra": "Anna Szczepańczyk-Baron +48 600 500 677 | tartak: +48 509 331 111 tartak@sordrew.pl | Monika Kosno (pakowanie) +48 519 685 210",
        "address": "ul. Sztygarska 26, 41-608 Świętochłowice + oddział Zabrze",
    },
    "Timber Trade": {
        "email": "biuro@timbertrade.pl",
        "phone": "+48 792 644 933",
        "phone_extra": "+48 666 644 933 (biuro), 792 644 933 (dział handlowy)",
        "address": "Nowa Wieś Rzeczna ul. Leśna 12C + Mysłowice ul. Katowicka 60",
    },
    "Pracownia Sztukatorska Adam Rzadkowski": {
        "email": "sztukatorstwo.ar@gmail.com",
        "phone": "+48 503 165 772",
        "contact_person": "Adam Rzadkowski",
        "position": "Właściciel",
        "address": "Wrocław",
    },
    "Jan Bud Drew Gont": {
        "phone": "+48 502 303 900",
        "contact_person": "Jan Bielak",
        "position": "Właściciel",
        "address": "Podsarnie 1A, 34-721 Raba Wyżna",
    },
    "Pracownia Stolarska Tomasz Kuziemko": {
        "phone": "+48 605 961 178",
        "contact_person": "Tomasz Kuziemko",
        "position": "Właściciel",
        "address": "Raczki k. Szczecina",
    },
    "Pracownia Stolarska Konar": {
        "contact_person": "Andrzej Zalewski",
        "position": "Właściciel",
        "address": "ul. Polnych Maków 1, 05-503 Baszkówka (k. Piaseczna)",
    },
    "Zakład Stolarski Piotrowscy": {
        "email": "jarekpiotrowski1970@wp.pl",
        "phone": "+48 694 188 848",
        "contact_person": "Jarosław Piotrowski",
        "position": "Właściciel",
        "address": "Zakole 6, 87-165 Cierpice, kuj-pom.",
    },
    "Tworzywo Concept": {
        "phone": "+48 604 771 295",
        "contact_person": "Paweł Jakimów",
        "position": "Właściciel",
        "address": "Kasztanowa 5, 32-406 Zakliczyn",
    },
    "Pracownia Stolarska Dworska 17": {
        "address": "ul. Dworska 17, Tłuczań k. Krakowa",
        "contact_person": "Robert Ławczys",
        "position": "Założyciel / Stolarz",
    },
    "Drewniane Klimaty": {
        "phone": "+48 508 288 032",
        "phone_extra": "+48 503 037 257 (doradztwo), +48 508 288 033 Barbara Krzyżewska (marketing)",
        "contact_person": "Krzysztof Kownacki",
        "position": "Właściciel",
        "address": "ul. Gdańska 27K, 83-034 Trąbki Wielkie (k. Trójmiasta)",
    },
    "Stolarnia Warszawska": {
        "email": "adrian@stolarniawarszawska.pl",
        "contact_person": "Adrian Troszyński",
        "position": "Stolarz / Projektant",
        "address": "ul. Strzygłowska 37, 04-872 Warszawa Wawer",
    },
    "Stolarstwo Samorodne": {
        "phone": "+48 600 353 936",
        "address": "Dębica, Podkarpackie",
        "position": "Stolarz artystyczny",
    },
    "Tabaszewski Renowacje": {
        "phone": "+48 607 983 373",
        "phone_extra": "+48 77 448 40 04 (BOK)",
        "contact_person": "Paweł Tabaszewski",
        "position": "Właściciel (Renovatio)",
        "address": "ul. Podolska 1A, 48-303 Nysa, Opolskie",
    },
    "Pason Wood Constructions": {
        "email": "ciesielstwo@mpason.pl",
        "phone": "+48 601 067 095",
        "address": "ul. Firmowa 1, 46-040 Schodnia (gmina Ozimek)",
    },
    "Akant Renowacje": {
        "email": "mmcakant@gmail.com",
        "phone": "+48 600 745 126",
        "phone_extra": "+48 604 596 416",
        "contact_person": "Magdalena Muszyńska-Chruścińska",
        "position": "Właściciel",
        "address": "ul. Pomorska 551, 92-735 Łódź",
    },
    "Remerus Liessen": {
        "phone": "+48 789 701 113",
        "phone_extra": "+48 665 640 511, +48 500 005 146",
        "address": "ul. Domaniewska 37/2.43, 02-672 Warszawa + oddział Kraków",
    },
    "Tartak Witkowscy - Szkutnictwo Tradycyjne": {
        "phone": "+48 43 842 86 00",
        "phone_extra": "+48 601 99 86 86 (sklep firmowy)",
        "contact_person": "Janina i Wacław Witkowscy",
        "position": "Właściciele",
        "address": "Rychłowice 21B, 98-300 Wieluń",
    },
    "Zakład Stolarski Paszkowycz": {
        "phone": "+48 508 297 244",
        "contact_person": "Krzysztof Paszkowycz",
        "position": "Właściciel",
        "address": "ul. Wypoczynkowa 2, 91-614 Łódź",
    },
    "SpaceML": {
        "phone": "+48 792 777 447",
        "contact_person": "Mateusz Moskal",
        "position": "Właściciel",
        "address": "ul. Długa 140, 33-131 Bobrowniki Wielkie",
    },
    "Sikor Home Bud": {
        "phone": "+48 794 777 470",
        "address": "ul. Wolfganga Amadeusza Mozarta 6, 02-736 Warszawa",
    },
    "Pracownia Stolarska Latzke": {
        "phone": "+48 692 093 912",
        "contact_person": "Jacek Latzke",
        "position": "Właściciel",
    },
    "Fabryka Drewna": {
        "phone": "+48 22 672 00 10",
        "email": "info@dombal.com.pl",
        "address": "ul. Kadetów 8, 03-987 Warszawa (Dombal Sp. z o.o.)",
        "extra": "Dział montażu konstrukcji drewnianych Dombal Sp. z o.o.",
    },
    "Dombal": {
        "phone": "+48 22 672 00 10",
        "email": "info@dombal.com.pl",
        "address": "ul. Kadetów 8, 03-987 Warszawa",
    },
    "Drew-Pol Sidzina": {
        "email": "admin@drewpolsidzina.pl",
        "address": "Sidzina, Małopolskie",
    },
    "Kerbe": {
        "email": "sklep@kerbe.pl",
        "phone": "+48 537 929 206",
        "address": "Juszczyn 319, 34-231 Juszczyn",
    },
    "Lokum Stolarstwo": {
        "phone": "+48 660 702 487",
        "contact_person": "Joel Gotowała",
        "position": "Właściciel (Studio Lokum Sp. z o.o.)",
        "address": "ul. Krakowska 124, 43-353 Porąbka",
    },
    "KaeR Projekt": {
        "email": "biuro@kaerprojekt.pl",
        "phone": "+48 500 252 343",
        "address": "Jana Długosza 7, Olsztyn",
    },
    "SRDK Studio": {
        "email": "biuro@srdkstudio.com",
        "phone": "+48 532 040 390",
        "address": "ul. Ksawerego Liskego 7, 50-345 Wrocław",
    },
    "Venifloor": {
        "email": "biuro@venifloor.com",
        "phone": "+48 730 203 013",
        "contact_person": "Adam Wystrychowski",
        "position": "Dział sprzedaży - Polska (Lubelskie/Małopolskie/Opolskie/Podkarpackie/Śląskie/Świętokrzyskie)",
        "phone_extra": "Adam Wystrychowski +48 533 707 240 aw@venifloor.com | Stanisław Kwiecień (export) +48 506 000 112 sk@venifloor.com | Gabriela Śliwicka +48 530 535 549",
    },
    "Andrewpol": {
        "email": "biuro@andrewpol.com.pl",
        "phone": "+48 85 683 46 38",
        "phone_extra": "+48 691 927 137, +48 609 777 009",
        "contact_person": "Andrzej Pryczynicz",
        "position": "Właściciel (Zakład Drzewny ANDREWPOL)",
        "address": "ul. Woskowa 9, 17-200 Hajnówka",
    },
    "Polish Floors (Pumori)": {
        "email": "biuro@polishfloors.pl",
        "phone": "+48 724 720 420",
        "address": "ul. Północna 21, 63-700 Krotoszyn",
    },
    "Podłogi Łańcuckie": {
        "address": "ul. Kolejowa 7, 37-100 Łańcut",
    },
    "Polskie Dęby": {
        "email": "biuro@parkietstudio.pl",
        "address": "PARKIET STUDIO S.C., ul. Bartycka 24/26, 00-716 Warszawa (wyłączny dystrybutor)",
    },
    "Centrum Parkietowe NOWAK": {
        "email": "biuro@centrum-parkietowe.pl",
        "phone": "+48 32 211 22 88",
        "phone_extra": "+48 33 819 36 22 (showroom Bielsko-Biała)",
        "address": "ul. 11 Listopada 32, 43-229 Pszczyna-Ćwiklice + showroom Partyzantów 72, Bielsko-Biała",
    },
    "Niezwykłe Drewno (Panele)": {
        "email": "kontakt@niezwykledrewno.pl",
        "phone": "+48 730 150 337",
        "contact_person": "Andrzej Szpilarowicz",
        "position": "Właściciel (Stare Drewno)",
        "address": "Brzeziczki 22, 21-050 Piaski",
    },
    "Domyzbali.pl (Biernacki)": {
        "email": "biernacki@domyzbali.pl",
        "phone": "+48 602 656 200",
        "phone_extra": "+48 602 656 300",
        "contact_person": "Stanisław Biernacki",
        "position": "Lider jakości / Właściciel",
        "address": "Łazy 95 k/Wyszkowa, 07-130 Łochów, mazowieckie",
    },
    "SLOW TATRY Boutique Resort": {
        "email": "recepcja@slowtatry.pl",
        "phone": "+48 791 606 686",
        "address": "Zakopane (najwyższa dzielnica, 1000m npm)",
    },
    "Pensjonat Nostalgia": {
        "email": "info@pensjonatnostalgia.pl",
        "phone": "+48 888 547 666",
        "address": "ul. Tyrolska 7, 58-564 Sosnówka (Karkonosze)",
    },
    "Chaty Świerkowe Wzgórze": {
        "email": "kontakt@chatyswierkowewzgorze.pl",
        "phone": "+48 721 242 524",
        "address": "ul. Podleśna 5, 58-540 Karpacz (830m npm)",
    },
    "Na Pograniczu Agroturystyka": {
        "phone": "+48 606 224 745",
        "address": "Lasówka 10, 57-500 Bystrzyca Kłodzka (Góry Stołowe)",
    },
    "Rysy Boutique Hotel": {
        "email": "recepcja@hotelrysy.pl",
        "phone": "+48 18 201 18 00",
        "address": "ul. Seweryna Goszczyńskiego 7, 34-500 Zakopane",
    },
    "Leśny Dwór Karpacz": {
        "email": "lesnydwor.karpacz@gmail.com",
        "phone": "+48 505 932 370",
        "phone_extra": "+48 730 932 370 | restauracja Mamma Mia +48 791 716 555",
        "contact_person": "Agnieszka i Damian Stachura",
        "position": "Właściciele (S.C.)",
        "address": "Karkonoska 1, 58-540 Karpacz",
    },
    "Jagodowa Polana": {
        "phone": "+48 601 612 770",
        "contact_person": "Marta",
        "position": "Gospodyni",
        "address": "ul. Na Studzionki 65, 34-434 Szlembark (powiat nowotarski)",
    },
    "Willa Fen Karpacz": {
        "phone": "+48 725 002 222",
        "phone_extra": "+48 886 506 349",
        "address": "ul. Marii Skłodowskiej-Curie 3a, 58-540 Karpacz",
    },
    "KOKO Ryku Agroturystyka": {
        "email": "info@kokoryku.pl",
        "phone": "+48 506 642 654",
        "address": "Bieganów 41, 57-400 Nowa Ruda (Dolny Śląsk)",
    },
    "Folkowy Dworek": {
        "phone": "+48 518 067 289",
        "address": "ul. Sądelska 23B, 34-531 Murzasichle",
    },
    "Tatrzański Bór - Apartamenty i Karczma": {
        "email": "tatrzanskibor@gmail.com",
        "phone": "+48 884 837 100",
        "phone_extra": "+48 18 208 42 08 (karczma) | +48 693 634 682 (eventy) | karczma@tatrzanskibor.pl",
        "address": "ul. Lichajówki 7-8, 34-531 Murzasichle",
    },
    "Nest Homes": {
        "phone": "+48 733 888 039",
        "address": "al. Kijowska 66/1, 30-079 Kraków",
    },
    "Marux Domy z Bali": {
        "phone": "+48 693 932 020",
        "phone_extra": "+48 74 853 50 52",
        "contact_person": "Krzysztof Burzyński",
        "position": "Właściciel",
        "address": "Witoszów Dolny 135B, 58-100 Świdnica",
    },
    "Dom z Bali Sp. z o.o. (Wimar)": {
        "phone": "+48 513 049 399",
        "phone_extra": "+48 508 604 950",
        "address": "Izabelin 1, 95-070 Aleksandrów Łódzki",
    },
    "Stasiak Domki drewniane": {
        "contact_person": "Ryszard Stasiak",
        "position": "Właściciel (Tartak-Stolarnia)",
        "address": "ul. Zamiejska 7, 11-520 Ryn, warm-maz.",
    },
    "Project-Dom": {
        "phone": "+48 606 371 325",
        "contact_person": "Adam Wisełka",
        "position": "Właściciel",
        "address": "ul. Papiernia 8, 43-450 Ustroń",
    },
    "Mawit": {
        "phone": "+48 666 054 197",
        "phone_extra": "+48 602 572 633",
        "contact_person": "Joanna i Bartłomiej Dyjas",
        "position": "Współwłaściciele (MAWIT S.C.)",
        "address": "ul. Maratońska 2, 41-407 Imielin, Śląsk",
    },
    "Timber Moon Polska": {
        "email": "sprzedaz@timbermoon.eu",
        "phone": "+48 607 329 677",
        "contact_person": "Piotr Jarosławski",
        "position": "Sprzedaż",
        "phone_extra": "Natalia Zwolenik (klient indyw./biz.) +48 607 707 523 kontakt@timbermoon.eu | Bartłomiej Per +48 607 708 536 doradca@timbermoon.eu | Piotr Jaros (sales export) +48 609 460 590 sales@timbermoon.eu",
        "address": "Narodowa 116, 32-080 Brzezie",
    },
}
